[build]
builder = "NIXPACKS"
buildCommand = "npm ci --no-cache && npm run build"

[build.nixpacksConfig]
nodeVersion = "20"

[deploy]
startCommand = "npx vite preview --host --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10